superbuild_add_project(expat
  CAN_USE_SYSTEM
  LICENSE_FILES
    COPYING
  SPDX_LICENSE_IDENTIFIER
    MIT
  SPDX_COPYRIGHT_TEXT
    "Copyright (c) 1998-2000 Thai Open Source Software Center Ltd and Clark Cooper"
    "Copyright (c) 2001-2022 Expat maintainers"
  CMAKE_ARGS
    -DEXPAT_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DEXPAT_BUILD_EXAMPLES:BOOL=OFF
    -DEXPAT_BUILD_PKGCONFIG:BOOL=ON
    -DEXPAT_BUILD_TESTS:BOOL=OFF
    -DEXPAT_BUILD_TOOLS:BOOL=OFF
    -DCMAKE_INSTALL_LIBDIR:PATH=lib
    -DCMAKE_INSTALL_NAME_DIR:PATH=<INSTALL_DIR>/lib
    -DCMAKE_INSTALL_RPATH:PATH=<INSTALL_DIR>/lib
)
