find_package(HDF5 REQUIRED)

superbuild_add_extra_cmake_args(
  -DHDF5_INCLUDE_DIRS=${HDF5_INCLUDE_DIRS}
  -DHDF5_DEFINITIONS=${HDF5_DEFINITIONS}
  -DHDF5_LIBRARIES=${HDF5_LIBRARIES}
  -DHDF5_HL_LIBRARIES=${HDF5_HL_LIBRARIES})
