if (BUILD_SHARED_LIBS)
  set(jsoncpp_shared -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF)
else()
  set(jsoncpp_shared -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_STATIC_LIBS:BOOL=ON)
endif()

superbuild_add_project(jsoncpp
  CMAKE_ARGS
    ${jsoncpp_shared}
    -DBUILD_TESTING:BOOL=OFF
    -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
    -DCMAKE_INSTALL_LIBDIR:STRING=lib
    -DCMAKE_INSTALL_NAME_DIR:PATH=<INSTALL_DIR>/lib
  LICENSE_FILES LICENSE)
