find_package(LAPACK REQUIRED)
set(BLAS_LIBRARIES ${BLAS_LIBRARIES}
  CACHE INTERNAL "" FORCE)
set(LAPACK_LIBRARIES ${LAPACK_LIBRARIES}
  CACHE INTERNAL "" FORCE)

string(REPLACE ";" "-*-" BLAS_LIBRARIES "${BLAS_LIBRARIES}")
string(REPLACE ";" "-*-" LAPACK_LIBRARIES "${LAPACK_LIBRARIES}")
string(REPLACE ";" "-*-" BLAS_LINKER_FLAGS "${BLAS_LINKER_FLAGS}")
string(REPLACE ";" "-*-" LAPACK_LINKER_FLAGS "${LAPACK_LINKER_FLAGS}")
superbuild_add_extra_cmake_args(
  -DBLAS_LIBRARIES=${BLAS_LIBRARIES}
  -DBLAS_LINKER_FLAGS=${BLAS_LINKER_FLAGS}
  -DLAPACK_LIBRARIES=${LAPACK_LIBRARIES}
  -DLAPACK_LINKER_FLAGS=${LAPACK_LINKER_FLAGS})
