superbuild_add_project(libxslt
  DEPENDS
    libxml2
  LICENSE_FILES
    Copyright
  SPDX_LICENSE_IDENTIFIER
    MIT
  SPDX_COPYRIGHT_TEXT
    "Copyright (C) 2001-2002 Daniel Veillard"
  CMAKE_ARGS
    -DCMAKE_INSTALL_LIBDIR:STRING=lib
    -DCMAKE_INSTALL_NAME_DIR:PATH=<INSTALL_DIR>/lib
    -DLIBXSLT_WITH_PYTHON:BOOL=OFF
    -DLIBXSLT_WITH_LZMA:BOOL=OFF
    -DLIBXSLT_WITH_MODULES:BOOL=OFF
    -DLIBXSLT_WITH_TESTS:BOOL=OFF)
