set(libxml2_with_iconv ON)
if (WIN32)
  set(libxml2_with_iconv OFF)
endif ()

superbuild_add_project(libxml2
  CAN_USE_SYSTEM
  LICENSE_FILES
    Copyright
  SPDX_LICENSE_IDENTIFIER
    MIT
  SPDX_COPYRIGHT_TEXT
    "Copyright (C) 1998-2012 Daniel Veillard"
  CMAKE_ARGS
    -DCMAKE_INSTALL_LIBDIR:STRING=lib
    -DCMAKE_INSTALL_NAME_DIR:PATH=<INSTALL_DIR>/lib
    -DLIBXML2_WITH_PYTHON:BOOL=OFF
    -DLIBXML2_WITH_ICONV:BOOL=${libxml2_with_iconv}
    -DLIBXML2_WITH_ICU:BOOL=OFF
    -DLIBXML2_WITH_LZMA:BOOL=OFF
    -DLIBXML2_WITH_ZLIB:BOOL=OFF
    -DLIBXML2_WITH_MODULES:BOOL=OFF
    -DLIBXML2_WITH_TESTS:BOOL=OFF)
