superbuild_add_project(netcdf
  DEPENDS hdf5 zlib

  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DBUILD_TESTING:BOOL=FALSE
    -DBUILD_UTILITIES:BOOL=FALSE
    -DUSE_SZIP:BOOL=OFF
    -DENABLE_DAP:BOOL=OFF)
