superbuild_add_project(openxrsdk
  DEPENDS jsoncpp
  CMAKE_ARGS
    -DDYNAMIC_LOADER:BOOL=ON
    -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
    -DCMAKE_INSTALL_LIBDIR:STRING=lib
  LICENSE_FILES LICENSE)
