superbuild_add_project_python(pythonaiohttp
  PACKAGE aiohttp
  DEPENDS pythonsetuptools pythonasynctimeout pythonattrs pythonchardet pythoncharsetnormalizer pythonmultidict pythontypingextensions pythonyarl pythonfrozenlist pythonaiosignal
  LICENSE_FILES LICENSE.txt)
