superbuild_add_project_python_pyproject(pythonversioneer
  PACKAGE
    versioneer
  DEPENDS
    pythonsetuptools
    pythonsetuptoolsscm
    pythontomli
  LICENSE_FILES
    LICENSE
  SPDX_LICENSE_IDENTIFIER
    Unlicense
  SPDX_COPYRIGHT_TEXT
    NONE
  )
