superbuild_add_project(zlib
  CAN_USE_SYSTEM
  LICENSE_FILES
    README
  CMAKE_ARGS
    -DCMAKE_MACOSX_RPATH:BOOL=FALSE
    -DCMAKE_INSTALL_NAME_DIR:PATH=<INSTALL_DIR>/lib
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS})
